extern const GeoLayout jers_waluigi_cap_6_Cap_Anim_State_Switch_opt1[];
extern const GeoLayout jers_waluigi_cap_geo[];
extern Lights1 jers_waluigi_cap_Emblem__EMBLEM__layer2_lights;
extern Lights1 jers_waluigi_cap_Cap__CAP__lights;
extern Lights1 jers_waluigi_cap_Cap_Dark__CAP__lights;
extern u8 jers_waluigi_cap_logo_cutout_waluigi_i8[];
extern u8 jers_waluigi_cap_logo_L_i8[];
extern Vtx jers_waluigi_cap_Cap_DL_mesh_layer_2_vtx_0[8];
extern Gfx jers_waluigi_cap_Cap_DL_mesh_layer_2_tri_0[];
extern Vtx jers_waluigi_cap_Cap_DL_mesh_layer_1_vtx_0[80];
extern Gfx jers_waluigi_cap_Cap_DL_mesh_layer_1_tri_0[];
extern Vtx jers_waluigi_cap_Cap_DL_mesh_layer_1_vtx_1[17];
extern Gfx jers_waluigi_cap_Cap_DL_mesh_layer_1_tri_1[];
extern Gfx mat_jers_waluigi_cap_Emblem__EMBLEM__layer2[];
extern Gfx mat_revert_jers_waluigi_cap_Emblem__EMBLEM__layer2[];
extern Gfx mat_jers_waluigi_cap_Cap__CAP_[];
extern Gfx mat_jers_waluigi_cap_Cap_Dark__CAP_[];
extern Gfx jers_waluigi_cap_Cap_DL_mesh_layer_2[];
extern Gfx jers_waluigi_cap_Cap_DL_mesh_layer_1[];
extern Gfx jers_waluigi_cap_material_revert_render_settings[];
