#include "src/game/envfx_snow.h"

const GeoLayout jers_waluigi_clone_Opacity_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ASM(LAYER_OPAQUE + 3, geo_mario_set_player_colors),
		GEO_ASM(LAYER_ALPHA + 3, geo_mario_set_player_colors),
		GEO_ASM(LAYER_TRANSPARENT + 3, geo_mario_set_player_colors),
		GEO_ASM(LAYER_OPAQUE << 2, geo_mirror_mario_backface_culling),
		GEO_ASM(LAYER_ALPHA << 2, geo_mirror_mario_backface_culling),
		GEO_ASM(LAYER_TRANSPARENT << 2, geo_mirror_mario_backface_culling),
		GEO_ASM(0, geo_mirror_mario_set_alpha),
		GEO_SWITCH_CASE(0, geo_switch_mario_stand_run),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 30, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_SCALE(LAYER_OPAQUE, 42936),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, jers_waluigi_clone_Butt_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, jers_waluigi_clone_Torso_skinned_mesh_layer_1),
							GEO_ASM(0, geo_move_mario_part_from_parent),
							GEO_ASM(0, geo_mario_tilt_torso),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 88, 15, 0, jers_waluigi_clone_Torso_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 132, 5, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ASM(0, geo_mario_head_rotation),
										GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_TRANSPARENT, jers_waluigi_clone_Head_DL_mesh_layer_1),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 99, 0, 79, NULL),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, jers_waluigi_clone_Left_Arm_Color_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_TRANSPARENT, jers_waluigi_clone_Left_Forearm_skinned_mesh_layer_1),
											GEO_ANIMATED_PART(LAYER_TRANSPARENT, 125, 0, 0, jers_waluigi_clone_Left_Forearm_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 140, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(1, geo_mario_hand_foot_scaler),
													GEO_SCALE(LAYER_FORCE, 65536),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_TRANSPARENT, jers_waluigi_clone_Left_Hand_DL_mesh_layer_1),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 100, 0, -79, NULL),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, jers_waluigi_clone_Right_Arm_Color_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_TRANSPARENT, jers_waluigi_clone_Right_Forearm_skinned_mesh_layer_1),
											GEO_ANIMATED_PART(LAYER_TRANSPARENT, 125, 0, 0, jers_waluigi_clone_Right_Forearm_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 140, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(0, geo_mario_hand_foot_scaler),
													GEO_SCALE(LAYER_FORCE, 65536),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_TRANSPARENT, jers_waluigi_clone_Right_Hand_DL_mesh_layer_1),
													GEO_CLOSE_NODE(),
													GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, -2, 12, 55, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, jers_waluigi_clone_Left_Thigh_Color_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, jers_waluigi_clone_Left_Leg_skinned_mesh_layer_1),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 139, 0, 0, jers_waluigi_clone_Left_Leg_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_TRANSPARENT, 142, 0, 0, jers_waluigi_clone_Left_Shoe_mesh_layer_1),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, -2, 12, -55, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, jers_waluigi_clone_Right_Thigh_Color_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, jers_waluigi_clone_Right_Leg_skinned_mesh_layer_1),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 139, 0, 0, jers_waluigi_clone_Right_Leg_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 142, 0, 0, NULL),
										GEO_OPEN_NODE(),
											GEO_ASM(2, geo_mario_hand_foot_scaler),
											GEO_SCALE(LAYER_FORCE, 65536),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, jers_waluigi_clone_Right_Shoe_DL_mesh_layer_1),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ASM((LAYER_OPAQUE << 2) | 1, geo_mirror_mario_backface_culling),
		GEO_ASM((LAYER_ALPHA << 2) | 1, geo_mirror_mario_backface_culling),
		GEO_ASM((LAYER_TRANSPARENT << 2) | 1, geo_mirror_mario_backface_culling),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout jers_waluigi_clone_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SCALE(LAYER_FORCE, 26236),
		GEO_OPEN_NODE(),
			GEO_ASM(0, geo_update_layer_transparency),
			GEO_SWITCH_CASE(2, geo_switch_anim_state),
			GEO_OPEN_NODE(),
				GEO_NODE_START(),
				GEO_OPEN_NODE(),
					GEO_ASM(LAYER_OPAQUE + 3, geo_mario_set_player_colors),
					GEO_ASM(LAYER_ALPHA + 3, geo_mario_set_player_colors),
					GEO_ASM(LAYER_TRANSPARENT + 3, geo_mario_set_player_colors),
					GEO_ASM(LAYER_OPAQUE << 2, geo_mirror_mario_backface_culling),
					GEO_ASM(LAYER_ALPHA << 2, geo_mirror_mario_backface_culling),
					GEO_ASM(LAYER_TRANSPARENT << 2, geo_mirror_mario_backface_culling),
					GEO_ASM(0, geo_mirror_mario_set_alpha),
					GEO_SWITCH_CASE(0, geo_switch_mario_stand_run),
					GEO_OPEN_NODE(),
						GEO_NODE_START(),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 30, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_SCALE(LAYER_OPAQUE, 42936),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, jers_waluigi_clone_Butt_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_OPAQUE, jers_waluigi_clone_Torso_skinned_mesh_layer_1),
										GEO_ASM(0, geo_move_mario_part_from_parent),
										GEO_ASM(0, geo_mario_tilt_torso),
										GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 88, 15, 0, jers_waluigi_clone_Torso_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 132, 5, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(0, geo_mario_head_rotation),
													GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_OPAQUE, jers_waluigi_clone_Head_DL_mesh_layer_1),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 99, 0, 79, NULL),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, jers_waluigi_clone_Left_Arm_Color_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_OPAQUE, jers_waluigi_clone_Left_Forearm_skinned_mesh_layer_1),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 125, 0, 0, jers_waluigi_clone_Left_Forearm_mesh_layer_1),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(LAYER_OPAQUE, 140, 0, 0, NULL),
															GEO_OPEN_NODE(),
																GEO_ASM(1, geo_mario_hand_foot_scaler),
																GEO_SCALE(LAYER_FORCE, 65536),
																GEO_OPEN_NODE(),
																	GEO_DISPLAY_LIST(LAYER_OPAQUE, jers_waluigi_clone_Left_Hand_DL_mesh_layer_1),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 100, 0, -79, NULL),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, jers_waluigi_clone_Right_Arm_Color_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_OPAQUE, jers_waluigi_clone_Right_Forearm_skinned_mesh_layer_1),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 125, 0, 0, jers_waluigi_clone_Right_Forearm_mesh_layer_1),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(LAYER_OPAQUE, 140, 0, 0, NULL),
															GEO_OPEN_NODE(),
																GEO_ASM(0, geo_mario_hand_foot_scaler),
																GEO_SCALE(LAYER_FORCE, 65536),
																GEO_OPEN_NODE(),
																	GEO_DISPLAY_LIST(LAYER_OPAQUE, jers_waluigi_clone_Right_Hand_DL_mesh_layer_1),
																GEO_CLOSE_NODE(),
																GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, -2, 12, 55, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, jers_waluigi_clone_Left_Thigh_Color_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, jers_waluigi_clone_Left_Leg_skinned_mesh_layer_1),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 139, 0, 0, jers_waluigi_clone_Left_Leg_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 142, 0, 0, jers_waluigi_clone_Left_Shoe_mesh_layer_1),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, -2, 12, -55, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, jers_waluigi_clone_Right_Thigh_Color_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, jers_waluigi_clone_Right_Leg_skinned_mesh_layer_1),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 139, 0, 0, jers_waluigi_clone_Right_Leg_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 142, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(2, geo_mario_hand_foot_scaler),
														GEO_SCALE(LAYER_FORCE, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_OPAQUE, jers_waluigi_clone_Right_Shoe_DL_mesh_layer_1),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ASM((LAYER_OPAQUE << 2) | 1, geo_mirror_mario_backface_culling),
					GEO_ASM((LAYER_ALPHA << 2) | 1, geo_mirror_mario_backface_culling),
					GEO_ASM((LAYER_TRANSPARENT << 2) | 1, geo_mirror_mario_backface_culling),
				GEO_CLOSE_NODE(),
				GEO_BRANCH(1, jers_waluigi_clone_Opacity_Switch_opt1),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, jers_waluigi_clone_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, jers_waluigi_clone_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
